directories:
  output: release
  buildResources: assets
appId: com.electron.meeting-notes
productName: Wingman AI
files:
  - filter:
      - dist/**/*
      - dist-electron/**/*
      - package.json
      - node_modules/**/*
extraResources:
  - from: assets/
    to: assets/
mac:
  category: public.app-category.productivity
  target:
    - target: dmg
      arch:
        - x64
        - arm64
  icon: assets/icons/mac/icon.icns
  hardenedRuntime: true
  entitlements: assets/entitlements.mac.plist
win:
  target:
    - target: nsis
      arch:
        - x64
        - ia32
    - target: portable
      arch:
        - x64
  icon: assets/icons/win/icon.ico
  requestedExecutionLevel: asInvoker
linux:
  target:
    - target: AppImage
      arch:
        - x64
    - target: deb
      arch:
        - x64
  icon: assets/icons/png/
  category: Office
nsis:
  oneClick: false
  perMachine: false
  allowToChangeInstallationDirectory: true
  deleteAppDataOnUninstall: false
publish:
  - provider: github
    owner: ibttf
    repo: interview-coder-frontend
electronVersion: 33.4.11
